FROM alpine:latest

RUN apk update && \
    apk add --no-cache ansible

RUN mkdir -p /root/ansible
RUN mkdir -p /root/.ssh/authorized_keys

#RUN chmod 600 /root/ansible/ansible_ed25519
# RUN ANSIBLE_CONFIG=/root/ansible/ansible.cfg